SET search_path TO sc_accac;

CREATE TABLE "tb_CTR" (
    "ni_id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_name" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE "tb_MDL" (
    "ni_id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_name"        varchar(100) NOT NULL,
    "cv_type"        varchar(50),
    "bh_img"         bytea,
    "ni_width"       integer,
    "ni_height"      integer,
    CONSTRAINT "chk_tb_MDL_ni_width"
        CHECK ("ni_width" IS NULL OR "ni_width" >= 0),
    CONSTRAINT "chk_tb_MDL_ni_height"
        CHECK ("ni_height" IS NULL OR "ni_height" >= 0)
);

CREATE TABLE "tb_STAT" (
    "ni_id"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_name"   varchar(50) NOT NULL UNIQUE,
    "cv_color"  integer NOT NULL,
    CONSTRAINT "chk_tb_STAT_cv_color"
        CHECK ("cv_color" BETWEEN 1 AND 4)
);

CREATE TABLE "tb_CITY" (
    "ni_id"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ni_CTR_id"  integer NOT NULL,
    "cv_name"    varchar(50) NOT NULL,
    CONSTRAINT "fk_tb_CTR_tb_CITY_ni_CTR_id"
        FOREIGN KEY ("ni_CTR_id") REFERENCES "tb_CTR"("ni_id"),
    CONSTRAINT "uq_tb_CITY_CTR_cv_name"
        UNIQUE ("ni_CTR_id", "cv_name")
);

CREATE TABLE "tb_ANT" (
    "ni_id"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ni_MDL_id"   integer NOT NULL,
    "ni_CITY_id"  integer NOT NULL,
    "ni_STAT_id"  integer NOT NULL,
    "cv_note"     varchar(255),
    CONSTRAINT "fk_tb_MDL_tb_ANT_ni_MDL_id"
        FOREIGN KEY ("ni_MDL_id") REFERENCES "tb_MDL"("ni_id"),
    CONSTRAINT "fk_tb_CITY_tb_ANT_ni_CITY_id"
        FOREIGN KEY ("ni_CITY_id") REFERENCES "tb_CITY"("ni_id"),
    CONSTRAINT "fk_tb_STAT_tb_ANT_ni_STAT_id"
        FOREIGN KEY ("ni_STAT_id") REFERENCES "tb_STAT"("ni_id")
);

CREATE TABLE "tb_LYT" (
    "ni_id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_name" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE "tb_CMP" (
    "ni_id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ni_ANT_id"     integer,
    "ni_CITY_id"    integer,
    "ni_CTR_id"     integer,
    "ni_LYT_id"     integer NOT NULL,
    "cv_type"       varchar(20),
    "ni_x"          integer,
    "ni_y"          integer,
    "ni_width"      integer,
    "ni_height"     integer,
    "cv_text"       varchar(200),
    "bl_visible"    boolean,

    CONSTRAINT "fk_tb_ANT_tb_CMP_ni_ANT_id"
        FOREIGN KEY ("ni_ANT_id") REFERENCES "tb_ANT"("ni_id"),

    CONSTRAINT "fk_tb_CITY_tb_CMP_ni_CITY_id"
        FOREIGN KEY ("ni_CITY_id") REFERENCES "tb_CITY"("ni_id"),

    CONSTRAINT "fk_tb_CTR_tb_CMP_ni_CTR_id"
        FOREIGN KEY ("ni_CTR_id") REFERENCES "tb_CTR"("ni_id"),

    CONSTRAINT "fk_tb_LYT_tb_CMP_ni_LYT_id"
        FOREIGN KEY ("ni_LYT_id") REFERENCES "tb_LYT"("ni_id"),

    CONSTRAINT "chk_tb_CMP_ni_x"
        CHECK ("ni_x" IS NULL OR "ni_x" >= 0),

    CONSTRAINT "chk_tb_CMP_ni_y"
        CHECK ("ni_y" IS NULL OR "ni_y" >= 0),

    CONSTRAINT "chk_tb_CMP_ni_width"
        CHECK ("ni_width" IS NULL OR "ni_width" > 0),

    CONSTRAINT "chk_tb_CMP_ni_height"
        CHECK ("ni_height" IS NULL OR "ni_height" > 0),

    CONSTRAINT "chk_tb_CMP_cv_type"
        CHECK ("cv_type" IN (
            'title',
            'rectangle_header',
            'header',
            'rectangle_city',
            'city',
            'rectangle_antenna',
            'antenna_text'
        ) OR "cv_type" IS NULL),

    CONSTRAINT "chk_tb_CMP_bl_visible"
        CHECK ("bl_visible" IN (TRUE, FALSE) OR "bl_visible" IS NULL)
);
